app = "saleor-storefront"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3000"
  NODE_ENV = "production"
  NEXT_PUBLIC_STOREFRONT_URL="https://saleor-storefront.fly.dev"
  NEXT_PUBLIC_SALEOR_API_URL="https://saleor-api.fly.dev/graphql/"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512