app = "saleor-api"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  PYTHONUNBUFFERED = "1"
  DASHBOARD_URL = "https://saleor-api.fly.dev/"  # Sửa URL để khớp với app name
  DEFAULT_FROM_EMAIL = "noreply@example.com"
  ALLOWED_HOSTS = "saleor-api.fly.dev,localhost,127.0.0.1,*"  # Thêm * và sửa domain
  ALLOWED_CORS_ORIGINS = "https://saleor-api.fly.dev"  # Sửa URL để khớp với app name

[http_service]
  internal_port = 8000  # Sửa từ 8080 thành 8000 để khớp với PORT
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

# Thêm health check rõ ràng
[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "30s"

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static"