app = "saleor-api"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  PYTHONUNBUFFERED = "1"
  ALLOWED_HOSTS = "saleor-api.fly.dev,localhost,127.0.0.1,*"
  ALLOWED_CORS_ORIGINS = "https://saleor-api.fly.dev"
  # Thêm debug để xem lỗi chi tiết
  DEBUG = "True"


# XÓA phần processes để sử dụng CMD trong Dockerfile
# [processes]
#  app = "uvicorn saleor.asgi:application --host=0.0.0.0 --port=8000 --workers=1 --lifespan=off"
[mounts]
  source = "saleor_media"
  destination = "/app/media"
[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ["app"]

# Đơn giản hóa - bỏ checks và statics nếu đang gây vấn đề

# Tăng RAM lên 1GB
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024