app = "saleor-api-worker"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  PYTHONUNBUFFERED = "1"

[processes]
  worker = "celery -A saleor worker --loglevel=info"

[[vm]]
  memory = "256MB"
  cpu_kind = "shared"
  processes = ["worker"]